import json, pathlib

ACCT = "0"
CONT = "0"

LANDING_HTML = r"""<script>
/*
 * FC - Attribution (Landing)  |  Step 1
 * Loads the Fintel analytics library and drops the first-party attribution cookie.
 *
 * Written as a programmatic loader rather than a bare <script src> + inline pair so
 * that fcpixel.attribution() cannot run before the library has finished loading, and
 * so a load failure is visible in the console instead of silent.
 */
(function () {
  var COOKIE_DOMAIN = "{{FC - Cookie Domain}}";
  var MERCHANT_REF  = "{{FC - Merchant Ref}}";
  var LIB = "https://cdn.fintelconnect.com/scripts/fcanalytics/v1.js";

  function run() {
    if (!window.fcpixel || typeof window.fcpixel.attribution !== "function") {
      if (window.console) console.error("[GTM][FC] fcpixel.attribution unavailable after load");
      return;
    }
    // fcpixel.attribution(queryParam, cookieDays, model, merchantRef, cookieDomain)
    window.fcpixel.attribution("finteltag", 10, "last", MERCHANT_REF, COOKIE_DOMAIN);
    if (window.console) {
      console.info("[GTM][FC] attribution fired, cookie domain =", COOKIE_DOMAIN);
    }
  }

  if (window.fcpixel && typeof window.fcpixel.attribution === "function") { run(); return; }

  var s = document.createElement("script");
  s.src = LIB;
  s.async = false;
  s.onload = run;
  s.onerror = function () {
    if (window.console) console.error("[GTM][FC] failed to load " + LIB);
  };
  document.head.appendChild(s);
})();
</script>"""

PIXEL_HTML = r"""<script>
/*
 * FC - Conversion Pixel (Thank You)  |  Step 2
 * Reads orderId and pid from the dataLayer and creates the Fintel record. The
 * cookie dropped on the landing page is what attributes it to a publisher.
 *
 * The order ID is generated by the page and pushed to the dataLayer. The fallback
 * below only covers the case where the tag is fired without one (e.g. a manual
 * trigger during testing), so the pixel never posts an empty order ID.
 */
(function () {
  var PROGRAM_ID   = {{FC - Program ID}};
  var MERCHANT_REF = "{{FC - Merchant Ref}}";
  var LIB = "https://app.fintelconnect.com/assets/scripts/fcanalytics.js";

  function generateOrderId() {
    var a = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789", s = "";
    for (var i = 0; i < 6; i++) s += a.charAt(Math.floor(Math.random() * a.length));
    return "FC-" + (new Date()).getTime() + "-" + s;
  }

  function clean(v, fallback) {
    if (v === undefined || v === null) return fallback;
    v = String(v);
    if (v === "" || v === "undefined" || v === "null") return fallback;
    return v;
  }

  var orderID = clean("{{DLV - orderId}}", generateOrderId());
  var pid     = clean("{{DLV - pid}}", "Rewards");

  function run() {
    if (!window.fcpixel || typeof window.fcpixel.pxl !== "function") {
      if (window.console) console.error("[GTM][FC] fcpixel.pxl unavailable after load");
      return;
    }
    // fcpixel.pxl(programId, orderID, pid, "", 0, 0, "", merchantRef)
    window.fcpixel.pxl(PROGRAM_ID, orderID, pid, "", 0, 0, "", MERCHANT_REF);
    if (window.console) {
      console.info("[GTM][FC] pixel fired", { orderID: orderID, pid: pid });
    }
  }

  if (window.fcpixel && typeof window.fcpixel.pxl === "function") { run(); return; }

  var s = document.createElement("script");
  s.src = LIB;
  s.async = false;
  s.onload = run;
  s.onerror = function () {
    if (window.console) console.error("[GTM][FC] failed to load " + LIB);
  };
  document.head.appendChild(s);
})();
</script>"""

COOKIE_DOMAIN_JS = r"""function () {
  /*
   * Cookie domain for fcpixel.attribution().
   *
   * A browser only accepts a cookie scoped to a domain the page is actually served
   * from, so this cannot be a literal — the harness runs on three kinds of host and
   * the correct value differs on each:
   *
   *   *.fctest.com        -> ".fctest.com"        dev testing (via /etc/hosts)
   *   *.fintelconnect.com -> ".fintelconnect.com" production
   *   anything else       -> the exact hostname   localhost, github.io, staging
   *
   * The fallback still writes a cookie so the rest of the flow stays testable, but
   * it is host-scoped and will not attribute on the Fintel platform.
   */
  var host = document.location.hostname || "";
  if (/(^|\.)fctest\.com$/i.test(host)) return ".fctest.com";
  if (/(^|\.)fintelconnect\.com$/i.test(host)) return ".fintelconnect.com";
  return host;
}"""


def tmpl(key, value):
    return {"type": "TEMPLATE", "key": key, "value": value}


def custom_html(tag_id, name, html, trigger_ids, notes):
    return {
        "accountId": ACCT,
        "containerId": CONT,
        "tagId": str(tag_id),
        "name": name,
        "type": "html",
        "notes": notes,
        "parameter": [
            tmpl("html", html),
            {"type": "BOOLEAN", "key": "supportDocumentWrite", "value": "false"},
        ],
        "fingerprint": "0",
        "firingTriggerId": [str(t) for t in trigger_ids],
        "tagFiringOption": "ONCE_PER_EVENT",
        "monitoringMetadata": {"type": "MAP"},
    }


def custom_event_trigger(trigger_id, name, event_name, notes):
    return {
        "accountId": ACCT,
        "containerId": CONT,
        "triggerId": str(trigger_id),
        "name": name,
        "type": "CUSTOM_EVENT",
        "notes": notes,
        "customEventFilter": [
            {
                "type": "EQUALS",
                "parameter": [
                    tmpl("arg0", "{{_event}}"),
                    tmpl("arg1", event_name),
                ],
            }
        ],
        "fingerprint": "0",
    }


def dlv(var_id, name, dl_name, notes):
    return {
        "accountId": ACCT,
        "containerId": CONT,
        "variableId": str(var_id),
        "name": name,
        "type": "v",
        "notes": notes,
        "parameter": [
            {"type": "INTEGER", "key": "dataLayerVersion", "value": "2"},
            {"type": "BOOLEAN", "key": "setDefaultValue", "value": "false"},
            tmpl("name", dl_name),
        ],
        "fingerprint": "0",
    }


def const(var_id, name, value, notes):
    return {
        "accountId": ACCT,
        "containerId": CONT,
        "variableId": str(var_id),
        "name": name,
        "type": "c",
        "notes": notes,
        "parameter": [tmpl("value", value)],
        "fingerprint": "0",
    }


def custom_js(var_id, name, js, notes):
    return {
        "accountId": ACCT,
        "containerId": CONT,
        "variableId": str(var_id),
        "name": name,
        "type": "jsm",
        "notes": notes,
        "parameter": [tmpl("javascript", js)],
        "fingerprint": "0",
    }


container_version = {
    "path": "accounts/%s/containers/%s/versions/0" % (ACCT, CONT),
    "accountId": ACCT,
    "containerId": CONT,
    "containerVersionId": "0",
    "name": "FC Bot Detection POC - v1",
    "description": (
        "Fintel Connect attribution + conversion pixel wired to custom dataLayer "
        "events for the bot-detection POC. Import into GTM-WFD2R889."
    ),
    "container": {
        "path": "accounts/%s/containers/%s" % (ACCT, CONT),
        "accountId": ACCT,
        "containerId": CONT,
        "name": "FC Bot Detection POC",
        "publicId": "GTM-WFD2R889",
        "usageContext": ["WEB"],
        "fingerprint": "0",
        "tagManagerUrl": "https://tagmanager.google.com/",
    },
    "tag": [
        custom_html(
            1,
            "FC - Attribution (Landing)",
            LANDING_HTML,
            [1],
            "Step 1. Drops the first-party attribution cookie. Fires on the custom "
            "event fc_landing_view, pushed by index.html before the container "
            "snippet.",
        ),
        custom_html(
            2,
            "FC - Conversion Pixel (Thank You)",
            PIXEL_HTML,
            [2],
            "Step 2. Creates the Fintel record and attributes it using the cookie "
            "from step 1. Fires on the custom event fc_application_submitted, "
            "pushed by thank-you.html before the container snippet.",
        ),
    ],
    "trigger": [
        custom_event_trigger(
            1, "CE - fc_landing_view", "fc_landing_view",
            "Custom event pushed on the landing page only.",
        ),
        custom_event_trigger(
            2, "CE - fc_application_submitted", "fc_application_submitted",
            "Custom event pushed on the thank-you page, carrying orderId and pid.",
        ),
    ],
    "variable": [
        dlv(1, "DLV - orderId", "orderId",
            "Order ID generated by the page on form submit and carried into the "
            "thank-you page. The pixel tag falls back to its own generator if empty."),
        dlv(2, "DLV - pid", "pid",
            "Product ID chosen on the application form. Defaults to Rewards."),
        const(3, "FC - Merchant Ref", "testmerchantFC",
              "Merchant reference passed to both fcpixel calls."),
        const(4, "FC - Program ID", "24490",
              "Fintel program ID, first argument of fcpixel.pxl()."),
        custom_js(5, "FC - Cookie Domain", COOKIE_DOMAIN_JS,
                  "Resolves the cookie domain per environment so the same tag works "
                  "in production and on the test host. See the comment in the code."),
    ],
    "builtInVariable": [
        {"accountId": ACCT, "containerId": CONT, "type": t, "name": n}
        for t, n in [
            ("PAGE_URL", "Page URL"),
            ("PAGE_HOSTNAME", "Page Hostname"),
            ("PAGE_PATH", "Page Path"),
            ("REFERRER", "Referrer"),
            ("EVENT", "Event"),
            ("DEBUG_MODE", "Debug Mode"),
        ]
    ],
    "fingerprint": "0",
}

export = {
    "exportFormatVersion": 2,
    "exportTime": "2026-08-05 00:00:00",
    "containerVersion": container_version,
}

out = pathlib.Path.home() / "Documents/fintel-gtm-bot-poc/gtm/fc-bot-detection-poc.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(export, indent=2) + "\n")

# validate round-trip
json.loads(out.read_text())
print("wrote", out, out.stat().st_size, "bytes — valid JSON")
